remove jx dependencies from git-merge

diff --git a/.github/workflows/environment-pullrequest.yaml b/.github/workflows/environment-pullrequest.yaml
--- a/.github/workflows/environment-pullrequest.yaml
+++ b/.github/workflows/environment-pullrequest.yaml
@@ -75,16 +75,40 @@ jobs:
         working-directory: "${{ github.workspace }}/source"
         run: |
           counter=0
+          BASE_BRANCH=origin/main
+
           until [ "$counter" -eq 3 ]; do
-            # lets avoid git rebase/merge conflicts on promotions
-            jx gitops git merge --rebase --merge-arg "-Xtheirs" && exit 0
+            echo "Attempt $((counter+1)) to rebase onto $BASE_BRANCH"
+
+            if git rebase "$BASE_BRANCH" -Xtheirs; then
+              exit 0
+            fi
+
             counter=$((counter+1))
-            git rebase --abort
-            if git log -1 --pretty=%B | grep -i regenerate; then
+
+            echo "Rebase failed, aborting"
+            git rebase --abort || true
+
+            if git log -1 --pretty=%B | grep -iq regenerate; then
+              echo "Dropping last regenerate commit"
               git reset --hard HEAD~1
             fi
           done
+
           exit 1
+
+          # counter=0
+          # until [ "$counter" -eq 3 ]; do
+          #   # lets avoid git rebase/merge conflicts on promotions
+          #   jx gitops git merge --rebase --merge-arg "-Xtheirs" && exit 0
+          #   counter=$((counter+1))
+          #   git rebase --abort
+          #   if git log -1 --pretty=%B | grep -i regenerate; then
+          #     git reset --hard HEAD~1
+          #   fi
+          # done
+          # exit 1
+          
       - id: "auth"
         name: "Authenticate to Google Cloud"
         uses: "google-github-actions/auth@v1"
